name: objc_unit_test
version: 0.0.1
language: objc
description: "使用模拟器运行您的单元测试"
tags:
 - flow
 - plugin
 - emulator
 - iOS

public: true

inputs:
  - name: FLOW_IOS_TEST_DEVICE		
    editable: true		    
    desc_cn: "测试设备选择"		
    desc_en: "Test device selection"
    options:
      - 'iPhone 6'=iPhone6
    default: 'iPhone 6'

outputs:

script_path: ./run.sh
