name: objc_unit_test
version: 0.0.1
language: objc
description: "使用模拟器运行您的单元测试"
tags:
 - flow
 - plugin
 - emulator
 - iOS

public: true

inputs:
  - name: FLOW_IOS_TEST_DEVICE
    editable: true    
    desc_cn: "测试设备选择"
    desc_en: "Test device selection"
    category: select
    options:
      - iPhone 5=iPhone 5
      - iPhone 5s=iPhone 5s
      - iPhone 6=iPhone 6
      - iPhone 6 Plus=iPhone 6 Plus
      - iPhone 6s=iPhone 6s
      - iPhone 6s Plus=iPhone 6s Plus
      - iPhone 7=iPhone 7
      - iPhone 7 Plus=iPhone 7 Plus
      - iPhone SE=iPhone SE
    default: "iPhone 6"

outputs:

script_path: ./run.sh
