name: objc_unit_test
version: 0.0.1
language: objc
description: Start an iOS emulator, which could run your unitTests in flow.ci
tags:
 - flow
 - plugin
 - emulator
 - iOS

public: true

# clone_in_docker: false
outputs:

script_path: ./run.sh
